### ISSUE TITLE
YARA vs. Sigma?

### ISSUE THREAD

**Issue by ruppde** [0x534a/dynmx#1]
Hi,

nice project! 

The rule format and what it's doing looks to me more like Sigma than YARA. Here's e.g. a Sigma rule to detect process hollowing:

```yaml
title: Possible Process Hollowing Image Loading
id: e32ce4f5-46c6-4c47-ba69-5de3c9193cd7
status: test
description: Detects Loading of samlib.dll, WinSCard.dll from untypical process e.g. through process hollowing by Mimikatz
references:
    - https://web.archive.org/web/20220815065318/https://cyberwardog.blogspot.com/2017/03/chronicles-of-threat-hunter-hunting-for.html
author: Markus Neis
date: 2018/01/07
modified: 2021/11/27
tags:
    - attack.defense_evasion
    - attack.t1574.002
logsource:
    category: image_load
    product: windows
detection:
    selection:
        Image|endswith: '\notepad.exe'
        ImageLoaded|endswith:
            - '\samlib.dll'
            - '\WinSCard.dll'
    condition: selection
falsepositives:
    - Very likely, needs more tuning
level: high
```
https://github.com/SigmaHQ/sigma/blob/c0332a9d96f6c7804fcc85dd706caed889446a62/rules/windows/image_load/image_load_susp_uncommon_image_load.yml
